services:
  - type: web
    name: colegio-app
    runtime: python
    repo: https://github.com/tu-usuario/colegio_app
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py