services:
  - type: web
    name: colegio-app
    runtime: python
    repo: https://github.com/TU_USUARIO/colegio_app
    plan: free
    region: oregon
    buildCommand: |
      uv sync --frozen && uv cache prune --ci
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: RENDER
        value: true
      - key: UV_SYSTEM_PYTHON
        value: true